import { createClient } from "@supabase/supabase-js";
import Link from "next/link";
import { 
  ArrowLeft, 
  Store, 
  MapPin, 
  CheckCircle2, 
  AlertTriangle, 
  Link as LinkIcon,
  Unlink,
  ExternalLink,
  ShoppingBag,
  DollarSign,
  Phone,
  Settings,
  ShieldAlert
} from "lucide-react";
import SubmitButton from "../../../components/SubmitButton";

// Secure Server Client
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// Note: Using Promise<{ id: string }> for Next.js 15 compatibility
export default async function StoreDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  
  // 1. Await the params to unlock the ID
  const resolvedParams = await params;

  // 2. Fetch the exact store and its linked orders for analytics
  const { data: store, error } = await supabaseAdmin
    .from('stores')
    .select(`
      *,
      orders ( total_amount, status )
    `)
    .eq('id', resolvedParams.id)
    .single();

  if (error || !store) {
    return (
      <div className="p-10 text-center">
        <h1 className="text-2xl font-bold text-slate-900">Store not found.</h1>
        <Link href="/admin/dashboard/stores" className="text-emerald-600 font-bold mt-4 inline-block hover:underline">
          &larr; Back to Stores Directory
        </Link>
      </div>
    );
  }

  // 3. Calculate Store Metrics
  const storeOrders = store.orders || [];
  const totalOrders = storeOrders.length;
  // Calculate total revenue generated by this store
  const totalRevenue = storeOrders.reduce((sum: number, order: any) => sum + Number(order.total_amount || 0), 0);

  // Formatting helpers
  const tDate = new Date(store.created_at).toLocaleString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric'
  });
  
  const isActive = store.status === 'active' || !store.status; // Default to active if status column is loose

  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto space-y-8">
      
      {/* HEADER SECTION */}
      <div>
        <Link href="/admin/dashboard/stores" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-800 transition-colors mb-4">
          <ArrowLeft className="h-4 w-4" /> Back to Stores
        </Link>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            {store.logo_url ? (
              <img src={store.logo_url} alt={store.name} className="h-16 w-16 rounded-2xl object-cover border border-slate-200 shadow-sm" />
            ) : (
              <div className="h-16 w-16 bg-indigo-50 rounded-2xl border border-indigo-100 flex items-center justify-center shrink-0">
                <Store className="h-8 w-8 text-indigo-500" />
              </div>
            )}
            <div>
              <h1 className="text-3xl font-black text-slate-900 flex items-center gap-3 tracking-tight">
                {store.name}
                {isActive ? (
                  <span className="text-xs px-3 py-1 bg-emerald-100 text-emerald-700 rounded-full flex items-center gap-1 font-bold tracking-wider uppercase">
                    <CheckCircle2 className="h-3 w-3" /> Active
                  </span>
                ) : (
                  <span className="text-xs px-3 py-1 bg-red-100 text-red-700 rounded-full flex items-center gap-1 font-bold tracking-wider uppercase">
                    <ShieldAlert className="h-3 w-3" /> Suspended
                  </span>
                )}
              </h1>
              <p className="text-slate-500 font-medium mt-1 font-mono text-sm">ID: {store.id}</p>
            </div>
          </div>
          
          <Link 
            href={`/store/${store.slug || store.id}`} 
            target="_blank"
            className="inline-flex items-center gap-2 px-6 py-3 bg-white border border-slate-200 rounded-xl text-slate-700 font-bold hover:bg-slate-50 transition-colors shadow-sm"
          >
            Visit Public Store <ExternalLink className="h-4 w-4" />
          </Link>
        </div>
      </div>

      {/* QUICK METRICS GRID */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-2">
            <ShoppingBag className="h-5 w-5 text-blue-500" />
            <h3 className="text-sm font-bold text-slate-500">Total Orders</h3>
          </div>
          <p className="text-2xl font-black text-slate-900">{totalOrders}</p>
        </div>

        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-2">
            <DollarSign className="h-5 w-5 text-emerald-500" />
            <h3 className="text-sm font-bold text-slate-500">Gross Volume</h3>
          </div>
          <p className="text-2xl font-black text-slate-900">Ksh {totalRevenue.toLocaleString()}</p>
        </div>

        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-2">
            {store.paystack_subaccount_code ? (
              <LinkIcon className="h-5 w-5 text-indigo-500" />
            ) : (
              <Unlink className="h-5 w-5 text-slate-400" />
            )}
            <h3 className="text-sm font-bold text-slate-500">Gateway Status</h3>
          </div>
          <p className="text-xl font-black text-slate-900 mt-1">
            {store.paystack_subaccount_code ? "Connected" : "Unlinked"}
          </p>
        </div>
      </div>

      {/* INFORMATION CARDS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Store Info */}
        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-indigo-50 rounded-xl"><Store className="h-5 w-5 text-indigo-600" /></div>
            <h2 className="text-sm font-bold text-slate-500 uppercase tracking-wider">Store Details</h2>
          </div>
          <ul className="space-y-4">
            <li><p className="text-xs text-slate-400 font-bold uppercase">Description</p><p className="font-medium text-slate-900 line-clamp-2">{store.description || "No description provided."}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Category</p><p className="font-medium text-slate-900 capitalize">{store.category || "Uncategorized"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Store Tier</p><p className="font-medium text-slate-900 capitalize">{store.tier || "Standard"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Offers Delivery</p><p className="font-medium text-slate-900">{store.offers_delivery ? "Yes" : "No"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Date Joined</p><p className="font-medium text-slate-900">{tDate}</p></li>
          </ul>
        </div>

        {/* Location & Contact */}
        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-orange-50 rounded-xl"><MapPin className="h-5 w-5 text-orange-600" /></div>
            <h2 className="text-sm font-bold text-slate-500 uppercase tracking-wider">Location & Contact</h2>
          </div>
          <ul className="space-y-4">
            <li><p className="text-xs text-slate-400 font-bold uppercase">County</p><p className="font-medium text-slate-900">{store.county || "Online / Not Set"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Town / City</p><p className="font-medium text-slate-900">{store.town || "N/A"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Specific Area</p><p className="font-medium text-slate-900">{store.area || "N/A"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Currency</p><p className="font-medium text-slate-900">{store.currency || "KES"}</p></li>
            <li><p className="text-xs text-slate-400 font-bold uppercase">Paystack Code</p><p className="font-medium font-mono text-slate-900">{store.paystack_subaccount_code || "Not Connected"}</p></li>
          </ul>
        </div>
      </div>

      {/* ADMIN ACTION PANEL - DANGER ZONE */}
      <div className="bg-white p-6 md:p-8 rounded-3xl border border-red-200 shadow-sm mt-8 border-t-4 border-t-red-500">
        <div className="flex items-start gap-4">
          <div className="p-3 bg-red-50 rounded-xl hidden sm:block">
            <Settings className="h-6 w-6 text-red-500" />
          </div>
          <div className="flex-1">
            <h2 className="text-xl font-black text-slate-900 mb-2">Admin Controls</h2>
            <p className="text-slate-500 font-medium mb-6 text-sm">
              Use these tools to manage this merchant's access to the platform. Suspending a store will immediately remove it from public view and disable checkout.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4">
              {/* Form 1: Suspend/Activate Store */}
              <form 
                action={async () => {
                  "use server";
                  // PLACEHOLDER: Connect your toggleStoreStatus action here
                  // await toggleStoreStatus(store.id, !isActive);
                  console.log("Toggle status for store:", store.id);
                }} 
              >
                <SubmitButton 
                  text={isActive ? "Suspend Store" : "Reactivate Store"} 
                  loadingText="Updating Status" 
                  variant={isActive ? "danger" : "success"} 
                />
              </form>

              {/* Form 2: Unlink Gateway */}
              {store.paystack_subaccount_code && (
                <form 
                  action={async () => {
                    "use server";
                    // PLACEHOLDER: Connect your unlinkGateway action here
                    console.log("Unlink gateway for store:", store.id);
                  }} 
                >
                  <SubmitButton 
                    text="Force Unlink Gateway" 
                    loadingText="Unlinking" 
                    variant="secondary" 
                  />
                </form>
              )}
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}